import { DatabaseState } from '../src/types.js';

export function getInitialSeedData(): DatabaseState {
  const users: DatabaseState['users'] = [
    {
      id: 'usr-1',
      name: 'Marina Morato',
      email: 'marinamorato120@gmail.com',
      role: 'admin',
      active: true,
    },
    {
      id: 'usr-2',
      name: 'Carlos Alberto Silva',
      email: 'carlos.silva@wmslog.com.br',
      role: 'supervisor',
      active: true,
    },
    {
      id: 'usr-3',
      name: 'Juliana Mendes',
      email: 'juliana.mendes@wmslog.com.br',
      role: 'operator',
      active: true,
    },
    {
      id: 'usr-4',
      name: 'Rodrigo Ferreira',
      email: 'rodrigo.ferreira@wmslog.com.br',
      role: 'inspector',
      active: true,
    },
  ];

  const settings: DatabaseState['settings'] = {
    technicalManager: 'Marina Morato',
    companyName: 'LogiTech Armazenagem & Distribuição',
    warehouseName: 'Centro de Distribuição Principal - CD 01',
    shelvesPerAisle: 5,
    aislesPerSector: 4,
    enableBarcodeScanner: true,
    autoSuggestPickingRoute: true,
  };

  // Generate locations: Sector A (Secos/Eletrônicos - alta rotação), Sector B (Alimentos/Perecíveis), Sector C (Peças Pesadas/Industrial), Sector D (Embalagens/Gerais)
  const sectors = [
    { id: 'A', name: 'Setor A - Eletrônicos & Alto Giro', aisles: 4, shelves: 5, distBase: 1 },
    { id: 'B', name: 'Setor B - Insumos & Giro Médio', aisles: 4, shelves: 5, distBase: 3 },
    { id: 'C', name: 'Setor C - Pesados & Industrial', aisles: 3, shelves: 4, distBase: 5 },
    { id: 'D', name: 'Setor D - Quarentena & Reserva', aisles: 2, shelves: 4, distBase: 7 },
  ];

  const locations: DatabaseState['locations'] = [];
  sectors.forEach((sec) => {
    for (let a = 1; a <= sec.aisles; a++) {
      const aisleStr = `C0${a}`;
      for (let s = 1; s <= sec.shelves; s++) {
        const label = `${sec.id}-${aisleStr}-P0${s}`;
        locations.push({
          id: `loc-${label.toLowerCase()}`,
          sectorId: sec.id,
          sectorName: sec.name,
          aisle: aisleStr,
          shelf: s,
          label,
          maxVolumeM3: s === 1 ? 4.5 : 2.5, // lower shelf holds more
          maxWeightKg: s === 1 ? 2000 : 800,
          distanceFromDispatch: sec.distBase + a * 0.5 + s * 0.1,
          status: 'active',
        });
      }
    }
  });

  const products: DatabaseState['products'] = [
    {
      id: 'prod-001',
      sku: 'EL-SMT-098',
      name: 'Smartphone Pro Max 256GB',
      description: 'Dispositivo móvel topo de linha, embalagem selada',
      category: 'Eletrônicos',
      unit: 'UN',
      minStock: 30,
      maxStock: 300,
      weightKg: 0.45,
      volumeM3: 0.002,
      abcClass: 'A',
      barcode: '7891000100981',
      createdAt: '2026-08-01T08:00:00.000Z',
      updatedAt: '2026-09-08T14:30:00.000Z',
    },
    {
      id: 'prod-002',
      sku: 'EL-FON-452',
      name: 'Fone de Ouvido Bluetooth Noise Cancelling',
      description: 'Headset sem fio com cancelamento ativo de ruído',
      category: 'Eletrônicos',
      unit: 'UN',
      minStock: 25,
      maxStock: 200,
      weightKg: 0.35,
      volumeM3: 0.003,
      abcClass: 'A',
      barcode: '7891000104523',
      createdAt: '2026-08-05T09:00:00.000Z',
      updatedAt: '2026-09-07T11:15:00.000Z',
    },
    {
      id: 'prod-003',
      sku: 'AUT-OLE-530',
      name: 'Óleo Sintético Motor 5W30 1L',
      description: 'Lubrificante sintético para motores de alta performance',
      category: 'Automotivo',
      unit: 'CX',
      minStock: 50,
      maxStock: 500,
      weightKg: 12.5,
      volumeM3: 0.035,
      abcClass: 'A',
      barcode: '7891000205307',
      createdAt: '2026-08-10T10:00:00.000Z',
      updatedAt: '2026-09-09T09:00:00.000Z',
    },
    {
      id: 'prod-004',
      sku: 'IND-MTR-750',
      name: 'Motor Elétrico Trifásico 7.5CV',
      description: 'Motor industrial carcaça de ferro fundido 60Hz',
      category: 'Industrial',
      unit: 'UN',
      minStock: 5,
      maxStock: 30,
      weightKg: 48.0,
      volumeM3: 0.12,
      abcClass: 'C',
      barcode: '7891000307504',
      createdAt: '2026-08-12T13:20:00.000Z',
      updatedAt: '2026-09-06T16:45:00.000Z',
    },
    {
      id: 'prod-005',
      sku: 'FAR-VIT-100',
      name: 'Suplemento Multivitamínico 100 Cápsulas',
      description: 'Frasco com selo de segurança e lote auditado',
      category: 'Farmacêutico',
      unit: 'CX',
      minStock: 40,
      maxStock: 400,
      weightKg: 3.2,
      volumeM3: 0.015,
      abcClass: 'B',
      barcode: '7891000401009',
      createdAt: '2026-08-15T08:30:00.000Z',
      updatedAt: '2026-09-08T10:10:00.000Z',
    },
    {
      id: 'prod-006',
      sku: 'EMB-CXC-001',
      name: 'Caixa de Papelão Reforçada 40x30x25cm',
      description: 'Embalagem de despacho padrão com onda dupla',
      category: 'Embalagens',
      unit: 'FARDO',
      minStock: 100,
      maxStock: 1000,
      weightKg: 15.0,
      volumeM3: 0.08,
      abcClass: 'B',
      barcode: '7891000500018',
      createdAt: '2026-08-18T15:00:00.000Z',
      updatedAt: '2026-09-08T17:00:00.000Z',
    },
  ];

  const stock: DatabaseState['stock'] = [
    {
      id: 'stk-001',
      productId: 'prod-001',
      sku: 'EL-SMT-098',
      productName: 'Smartphone Pro Max 256GB',
      locationId: 'loc-a-c01-p02',
      locationLabel: 'A-C01-P02',
      sectorId: 'A',
      aisle: 'C01',
      shelf: 2,
      lot: 'LT-2026-08-SMT01',
      manufacturingDate: '2026-07-20',
      expiryDate: '2028-07-20',
      quantity: 120,
      reservedQuantity: 15,
      unit: 'UN',
      status: 'available',
      lastUpdated: '2026-09-08T14:30:00.000Z',
    },
    {
      id: 'stk-002',
      productId: 'prod-001',
      sku: 'EL-SMT-098',
      productName: 'Smartphone Pro Max 256GB',
      locationId: 'loc-a-c01-p03',
      locationLabel: 'A-C01-P03',
      sectorId: 'A',
      aisle: 'C01',
      shelf: 3,
      lot: 'LT-2026-08-SMT02',
      manufacturingDate: '2026-08-01',
      expiryDate: '2028-08-01',
      quantity: 65,
      reservedQuantity: 0,
      unit: 'UN',
      status: 'available',
      lastUpdated: '2026-09-07T09:00:00.000Z',
    },
    {
      id: 'stk-003',
      productId: 'prod-002',
      sku: 'EL-FON-452',
      productName: 'Fone de Ouvido Bluetooth Noise Cancelling',
      locationId: 'loc-a-c02-p02',
      locationLabel: 'A-C02-P02',
      sectorId: 'A',
      aisle: 'C02',
      shelf: 2,
      lot: 'LT-2026-07-FON09',
      manufacturingDate: '2026-07-10',
      expiryDate: '2029-07-10',
      quantity: 94,
      reservedQuantity: 10,
      unit: 'UN',
      status: 'available',
      lastUpdated: '2026-09-07T11:15:00.000Z',
    },
    {
      id: 'stk-004',
      productId: 'prod-003',
      sku: 'AUT-OLE-530',
      productName: 'Óleo Sintético Motor 5W30 1L',
      locationId: 'loc-b-c01-p01',
      locationLabel: 'B-C01-P01',
      sectorId: 'B',
      aisle: 'C01',
      shelf: 1,
      lot: 'LT-2026-08-OLE22',
      manufacturingDate: '2026-08-05',
      expiryDate: '2030-08-05',
      quantity: 180,
      reservedQuantity: 20,
      unit: 'CX',
      status: 'available',
      lastUpdated: '2026-09-09T09:00:00.000Z',
    },
    {
      id: 'stk-005',
      productId: 'prod-004',
      sku: 'IND-MTR-750',
      productName: 'Motor Elétrico Trifásico 7.5CV',
      locationId: 'loc-c-c01-p01',
      locationLabel: 'C-C01-P01',
      sectorId: 'C',
      aisle: 'C01',
      shelf: 1,
      lot: 'LT-2026-06-MTR03',
      manufacturingDate: '2026-06-15',
      expiryDate: undefined,
      quantity: 14,
      reservedQuantity: 2,
      unit: 'UN',
      status: 'available',
      lastUpdated: '2026-09-06T16:45:00.000Z',
    },
    {
      id: 'stk-006',
      productId: 'prod-005',
      sku: 'FAR-VIT-100',
      productName: 'Suplemento Multivitamínico 100 Cápsulas',
      locationId: 'loc-b-c02-p02',
      locationLabel: 'B-C02-P02',
      sectorId: 'B',
      aisle: 'C02',
      shelf: 2,
      lot: 'LT-2026-08-FAR11',
      manufacturingDate: '2026-08-02',
      expiryDate: '2027-08-02',
      quantity: 210,
      reservedQuantity: 25,
      unit: 'CX',
      status: 'available',
      lastUpdated: '2026-09-08T10:10:00.000Z',
    },
    {
      id: 'stk-007',
      productId: 'prod-006',
      sku: 'EMB-CXC-001',
      productName: 'Caixa de Papelão Reforçada 40x30x25cm',
      locationId: 'loc-d-c01-p01',
      locationLabel: 'D-C01-P01',
      sectorId: 'D',
      aisle: 'C01',
      shelf: 1,
      lot: 'LT-2026-08-EMB05',
      manufacturingDate: '2026-08-01',
      expiryDate: undefined,
      quantity: 450,
      reservedQuantity: 0,
      unit: 'FARDO',
      status: 'available',
      lastUpdated: '2026-09-08T17:00:00.000Z',
    },
  ];

  const movements: DatabaseState['movements'] = [
    {
      id: 'mov-001',
      timestamp: '2026-09-05T09:15:00.000Z',
      type: 'INBOUND',
      productId: 'prod-001',
      sku: 'EL-SMT-098',
      productName: 'Smartphone Pro Max 256GB',
      lot: 'LT-2026-08-SMT01',
      quantity: 150,
      previousBalance: 0,
      newBalance: 150,
      toLocationLabel: 'A-C01-P02',
      documentRef: 'NF-e 44921',
      reason: 'Recebimento de Fornecedor TechDistribuidora',
      operatorName: 'Juliana Mendes',
      technicalManager: 'Marina Morato',
    },
    {
      id: 'mov-002',
      timestamp: '2026-09-06T11:40:00.000Z',
      type: 'INBOUND',
      productId: 'prod-003',
      sku: 'AUT-OLE-530',
      productName: 'Óleo Sintético Motor 5W30 1L',
      lot: 'LT-2026-08-OLE22',
      quantity: 200,
      previousBalance: 0,
      newBalance: 200,
      toLocationLabel: 'B-C01-P01',
      documentRef: 'NF-e 88102',
      reason: 'Carga Recebida - PetroLubes Brasil',
      operatorName: 'Carlos Alberto Silva',
      technicalManager: 'Marina Morato',
    },
    {
      id: 'mov-003',
      timestamp: '2026-09-07T14:10:00.000Z',
      type: 'OUTBOUND',
      productId: 'prod-001',
      sku: 'EL-SMT-098',
      productName: 'Smartphone Pro Max 256GB',
      lot: 'LT-2026-08-SMT01',
      quantity: 15,
      previousBalance: 150,
      newBalance: 135,
      fromLocationLabel: 'A-C01-P02',
      documentRef: 'PED-EXP-9002',
      reason: 'Expedição Pedido e-Commerce Varejo',
      operatorName: 'Juliana Mendes',
      technicalManager: 'Marina Morato',
    },
    {
      id: 'mov-004',
      timestamp: '2026-09-08T10:00:00.000Z',
      type: 'ADJUSTMENT',
      productId: 'prod-002',
      sku: 'EL-FON-452',
      productName: 'Fone de Ouvido Bluetooth Noise Cancelling',
      lot: 'LT-2026-07-FON09',
      quantity: -2,
      previousBalance: 96,
      newBalance: 94,
      fromLocationLabel: 'A-C02-P02',
      documentRef: 'INV-ROT-2026-09',
      reason: 'Ajuste de inventário rotativo - Avaria de embalagem descartada',
      operatorName: 'Rodrigo Ferreira',
      technicalManager: 'Marina Morato',
    },
    {
      id: 'mov-005',
      timestamp: '2026-09-09T08:30:00.000Z',
      type: 'TRANSFER',
      productId: 'prod-001',
      sku: 'EL-SMT-098',
      productName: 'Smartphone Pro Max 256GB',
      lot: 'LT-2026-08-SMT02',
      quantity: 20,
      previousBalance: 65,
      newBalance: 65,
      fromLocationLabel: 'A-C01-P04',
      toLocationLabel: 'A-C01-P03',
      documentRef: 'TRF-INT-014',
      reason: 'Otimização ergonômica de prateleira (descida de nível)',
      operatorName: 'Juliana Mendes',
      technicalManager: 'Marina Morato',
    },
  ];

  const pickingOrders: DatabaseState['pickingOrders'] = [
    {
      id: 'ord-1001',
      orderNumber: 'PK-2026-0041',
      customer: 'TechSul Megastore Ltda',
      priority: 'urgent',
      status: 'in_progress',
      createdAt: '2026-09-09T09:15:00.000Z',
      startedAt: '2026-09-09T09:30:00.000Z',
      assignedTo: 'Juliana Mendes',
      technicalManager: 'Marina Morato',
      totalItems: 3,
      pickedItems: 2,
      notes: 'Despacho aéreo expresso - Doca 02',
      dispatchDock: 'Doca 02 - Saída Expresso',
      items: [
        {
          id: 'pki-01',
          productId: 'prod-001',
          sku: 'EL-SMT-098',
          productName: 'Smartphone Pro Max 256GB',
          locationId: 'loc-a-c01-p02',
          locationLabel: 'A-C01-P02',
          sector: 'A',
          aisle: 'C01',
          shelf: 2,
          lot: 'LT-2026-08-SMT01',
          quantityRequired: 5,
          quantityPicked: 5,
          status: 'picked',
          pickedAt: '2026-09-09T09:35:00.000Z',
          pickedBy: 'Juliana Mendes',
        },
        {
          id: 'pki-02',
          productId: 'prod-002',
          sku: 'EL-FON-452',
          productName: 'Fone de Ouvido Bluetooth Noise Cancelling',
          locationId: 'loc-a-c02-p02',
          locationLabel: 'A-C02-P02',
          sector: 'A',
          aisle: 'C02',
          shelf: 2,
          lot: 'LT-2026-07-FON09',
          quantityRequired: 4,
          quantityPicked: 4,
          status: 'picked',
          pickedAt: '2026-09-09T09:42:00.000Z',
          pickedBy: 'Juliana Mendes',
        },
        {
          id: 'pki-03',
          productId: 'prod-005',
          sku: 'FAR-VIT-100',
          productName: 'Suplemento Multivitamínico 100 Cápsulas',
          locationId: 'loc-b-c02-p02',
          locationLabel: 'B-C02-P02',
          sector: 'B',
          aisle: 'C02',
          shelf: 2,
          lot: 'LT-2026-08-FAR11',
          quantityRequired: 10,
          quantityPicked: 0,
          status: 'pending',
        },
      ],
    },
    {
      id: 'ord-1002',
      orderNumber: 'PK-2026-0042',
      customer: 'AutoPeças & Mecânica Central',
      priority: 'high',
      status: 'pending',
      createdAt: '2026-09-09T10:00:00.000Z',
      assignedTo: 'Carlos Alberto Silva',
      technicalManager: 'Marina Morato',
      totalItems: 2,
      pickedItems: 0,
      notes: 'Carregamento paletizado',
      dispatchDock: 'Doca 01 - Carga Geral',
      items: [
        {
          id: 'pki-04',
          productId: 'prod-003',
          sku: 'AUT-OLE-530',
          productName: 'Óleo Sintético Motor 5W30 1L',
          locationId: 'loc-b-c01-p01',
          locationLabel: 'B-C01-P01',
          sector: 'B',
          aisle: 'C01',
          shelf: 1,
          lot: 'LT-2026-08-OLE22',
          quantityRequired: 20,
          quantityPicked: 0,
          status: 'pending',
        },
        {
          id: 'pki-05',
          productId: 'prod-004',
          sku: 'IND-MTR-750',
          productName: 'Motor Elétrico Trifásico 7.5CV',
          locationId: 'loc-c-c01-p01',
          locationLabel: 'C-C01-P01',
          sector: 'C',
          aisle: 'C01',
          shelf: 1,
          lot: 'LT-2026-06-MTR03',
          quantityRequired: 2,
          quantityPicked: 0,
          status: 'pending',
        },
      ],
    },
    {
      id: 'ord-1003',
      orderNumber: 'PK-2026-0039',
      customer: 'Distribuidora Farmacêutica Vida & Saúde',
      priority: 'normal',
      status: 'completed',
      createdAt: '2026-09-08T13:00:00.000Z',
      startedAt: '2026-09-08T13:10:00.000Z',
      completedAt: '2026-09-08T13:28:00.000Z',
      assignedTo: 'Juliana Mendes',
      technicalManager: 'Marina Morato',
      totalItems: 2,
      pickedItems: 2,
      notes: 'Conferido com leitor de código de barras',
      dispatchDock: 'Doca 03 - Farmacêuticos',
      items: [
        {
          id: 'pki-06',
          productId: 'prod-005',
          sku: 'FAR-VIT-100',
          productName: 'Suplemento Multivitamínico 100 Cápsulas',
          locationId: 'loc-b-c02-p02',
          locationLabel: 'B-C02-P02',
          sector: 'B',
          aisle: 'C02',
          shelf: 2,
          lot: 'LT-2026-08-FAR11',
          quantityRequired: 15,
          quantityPicked: 15,
          status: 'picked',
          pickedAt: '2026-09-08T13:20:00.000Z',
          pickedBy: 'Juliana Mendes',
        },
        {
          id: 'pki-07',
          productId: 'prod-006',
          sku: 'EMB-CXC-001',
          productName: 'Caixa de Papelão Reforçada 40x30x25cm',
          locationId: 'loc-d-c01-p01',
          locationLabel: 'D-C01-P01',
          sector: 'D',
          aisle: 'C01',
          shelf: 1,
          lot: 'LT-2026-08-EMB05',
          quantityRequired: 5,
          quantityPicked: 5,
          status: 'picked',
          pickedAt: '2026-09-08T13:26:00.000Z',
          pickedBy: 'Juliana Mendes',
        },
      ],
    },
  ];

  return {
    users,
    products,
    locations,
    stock,
    movements,
    pickingOrders,
    settings,
    backupHistory: [
      {
        id: 'bkp-initial',
        timestamp: '2026-09-08T00:00:00.000Z',
        note: 'Backup automático de rotina - Integridade confirmada',
        recordCount: products.length + locations.length + stock.length + movements.length,
      },
    ],
  };
}
